// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Subprocess.proto

package com.mackenziehigh.socius.gpb;

public final class subprocess_m {
  private subprocess_m() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProcessRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mackenziehigh.socius.subprocess.ProcessRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string staticId = 1;</code>
     */
    boolean hasStaticId();
    /**
     * <code>optional string staticId = 1;</code>
     */
    java.lang.String getStaticId();
    /**
     * <code>optional string staticId = 1;</code>
     */
    com.google.protobuf.ByteString
        getStaticIdBytes();

    /**
     * <code>optional string dynamicId = 2;</code>
     */
    boolean hasDynamicId();
    /**
     * <code>optional string dynamicId = 2;</code>
     */
    java.lang.String getDynamicId();
    /**
     * <code>optional string dynamicId = 2;</code>
     */
    com.google.protobuf.ByteString
        getDynamicIdBytes();

    /**
     * <code>repeated string arguments = 3;</code>
     */
    java.util.List<java.lang.String>
        getArgumentsList();
    /**
     * <code>repeated string arguments = 3;</code>
     */
    int getArgumentsCount();
    /**
     * <code>repeated string arguments = 3;</code>
     */
    java.lang.String getArguments(int index);
    /**
     * <code>repeated string arguments = 3;</code>
     */
    com.google.protobuf.ByteString
        getArgumentsBytes(int index);

    /**
     * <code>repeated string stdin = 4;</code>
     */
    java.util.List<java.lang.String>
        getStdinList();
    /**
     * <code>repeated string stdin = 4;</code>
     */
    int getStdinCount();
    /**
     * <code>repeated string stdin = 4;</code>
     */
    java.lang.String getStdin(int index);
    /**
     * <code>repeated string stdin = 4;</code>
     */
    com.google.protobuf.ByteString
        getStdinBytes(int index);
  }
  /**
   * Protobuf type {@code com.mackenziehigh.socius.subprocess.ProcessRequest}
   */
  public  static final class ProcessRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mackenziehigh.socius.subprocess.ProcessRequest)
      ProcessRequestOrBuilder {
    // Use ProcessRequest.newBuilder() to construct.
    private ProcessRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProcessRequest() {
      staticId_ = "";
      dynamicId_ = "";
      arguments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      stdin_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProcessRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              staticId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              dynamicId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                arguments_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              arguments_.add(bs);
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                stdin_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              stdin_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          arguments_ = arguments_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          stdin_ = stdin_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mackenziehigh.socius.gpb.subprocess_m.internal_static_com_mackenziehigh_socius_subprocess_ProcessRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mackenziehigh.socius.gpb.subprocess_m.internal_static_com_mackenziehigh_socius_subprocess_ProcessRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest.class, com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest.Builder.class);
    }

    private int bitField0_;
    public static final int STATICID_FIELD_NUMBER = 1;
    private volatile java.lang.Object staticId_;
    /**
     * <code>optional string staticId = 1;</code>
     */
    public boolean hasStaticId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string staticId = 1;</code>
     */
    public java.lang.String getStaticId() {
      java.lang.Object ref = staticId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          staticId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string staticId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStaticIdBytes() {
      java.lang.Object ref = staticId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        staticId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DYNAMICID_FIELD_NUMBER = 2;
    private volatile java.lang.Object dynamicId_;
    /**
     * <code>optional string dynamicId = 2;</code>
     */
    public boolean hasDynamicId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string dynamicId = 2;</code>
     */
    public java.lang.String getDynamicId() {
      java.lang.Object ref = dynamicId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dynamicId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dynamicId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDynamicIdBytes() {
      java.lang.Object ref = dynamicId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dynamicId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARGUMENTS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList arguments_;
    /**
     * <code>repeated string arguments = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getArgumentsList() {
      return arguments_;
    }
    /**
     * <code>repeated string arguments = 3;</code>
     */
    public int getArgumentsCount() {
      return arguments_.size();
    }
    /**
     * <code>repeated string arguments = 3;</code>
     */
    public java.lang.String getArguments(int index) {
      return arguments_.get(index);
    }
    /**
     * <code>repeated string arguments = 3;</code>
     */
    public com.google.protobuf.ByteString
        getArgumentsBytes(int index) {
      return arguments_.getByteString(index);
    }

    public static final int STDIN_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList stdin_;
    /**
     * <code>repeated string stdin = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStdinList() {
      return stdin_;
    }
    /**
     * <code>repeated string stdin = 4;</code>
     */
    public int getStdinCount() {
      return stdin_.size();
    }
    /**
     * <code>repeated string stdin = 4;</code>
     */
    public java.lang.String getStdin(int index) {
      return stdin_.get(index);
    }
    /**
     * <code>repeated string stdin = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStdinBytes(int index) {
      return stdin_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, staticId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dynamicId_);
      }
      for (int i = 0; i < arguments_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, arguments_.getRaw(i));
      }
      for (int i = 0; i < stdin_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, stdin_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, staticId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dynamicId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < arguments_.size(); i++) {
          dataSize += computeStringSizeNoTag(arguments_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getArgumentsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stdin_.size(); i++) {
          dataSize += computeStringSizeNoTag(stdin_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getStdinList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest)) {
        return super.equals(obj);
      }
            com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest other = (com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest) obj;

      boolean result = true;
      result = result && (hasStaticId() == other.hasStaticId());
      if (hasStaticId()) {
        result = result && getStaticId()
            .equals(other.getStaticId());
      }
      result = result && (hasDynamicId() == other.hasDynamicId());
      if (hasDynamicId()) {
        result = result && getDynamicId()
            .equals(other.getDynamicId());
      }
      result = result && getArgumentsList()
          .equals(other.getArgumentsList());
      result = result && getStdinList()
          .equals(other.getStdinList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStaticId()) {
        hash = (37 * hash) + STATICID_FIELD_NUMBER;
        hash = (53 * hash) + getStaticId().hashCode();
      }
      if (hasDynamicId()) {
        hash = (37 * hash) + DYNAMICID_FIELD_NUMBER;
        hash = (53 * hash) + getDynamicId().hashCode();
      }
      if (getArgumentsCount() > 0) {
        hash = (37 * hash) + ARGUMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getArgumentsList().hashCode();
      }
      if (getStdinCount() > 0) {
        hash = (37 * hash) + STDIN_FIELD_NUMBER;
        hash = (53 * hash) + getStdinList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mackenziehigh.socius.subprocess.ProcessRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mackenziehigh.socius.subprocess.ProcessRequest)
        com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return  com.mackenziehigh.socius.gpb.subprocess_m.internal_static_com_mackenziehigh_socius_subprocess_ProcessRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return  com.mackenziehigh.socius.gpb.subprocess_m.internal_static_com_mackenziehigh_socius_subprocess_ProcessRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest.class, com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest.Builder.class);
      }

      // Construct using com.mackenziehigh.socius.subprocess.Subprocess.ProcessRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        staticId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        dynamicId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        arguments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        stdin_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return  com.mackenziehigh.socius.gpb.subprocess_m.internal_static_com_mackenziehigh_socius_subprocess_ProcessRequest_descriptor;
      }

      public com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest getDefaultInstanceForType() {
        return  com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest.getDefaultInstance();
      }

      public com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest build() {
                com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest buildPartial() {
                com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest result = new com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.staticId_ = staticId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dynamicId_ = dynamicId_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          arguments_ = arguments_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.arguments_ = arguments_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          stdin_ = stdin_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.stdin_ = stdin_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest) {
          return mergeFrom((com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest other) {
        if (other == com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest.getDefaultInstance()) return this;
        if (other.hasStaticId()) {
          bitField0_ |= 0x00000001;
          staticId_ = other.staticId_;
          onChanged();
        }
        if (other.hasDynamicId()) {
          bitField0_ |= 0x00000002;
          dynamicId_ = other.dynamicId_;
          onChanged();
        }
        if (!other.arguments_.isEmpty()) {
          if (arguments_.isEmpty()) {
            arguments_ = other.arguments_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureArgumentsIsMutable();
            arguments_.addAll(other.arguments_);
          }
          onChanged();
        }
        if (!other.stdin_.isEmpty()) {
          if (stdin_.isEmpty()) {
            stdin_ = other.stdin_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureStdinIsMutable();
            stdin_.addAll(other.stdin_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
                com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object staticId_ = "";
      /**
       * <code>optional string staticId = 1;</code>
       */
      public boolean hasStaticId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string staticId = 1;</code>
       */
      public java.lang.String getStaticId() {
        java.lang.Object ref = staticId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            staticId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string staticId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStaticIdBytes() {
        java.lang.Object ref = staticId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          staticId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string staticId = 1;</code>
       */
      public Builder setStaticId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        staticId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string staticId = 1;</code>
       */
      public Builder clearStaticId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        staticId_ = getDefaultInstance().getStaticId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string staticId = 1;</code>
       */
      public Builder setStaticIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        staticId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dynamicId_ = "";
      /**
       * <code>optional string dynamicId = 2;</code>
       */
      public boolean hasDynamicId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string dynamicId = 2;</code>
       */
      public java.lang.String getDynamicId() {
        java.lang.Object ref = dynamicId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dynamicId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dynamicId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDynamicIdBytes() {
        java.lang.Object ref = dynamicId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dynamicId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dynamicId = 2;</code>
       */
      public Builder setDynamicId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dynamicId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dynamicId = 2;</code>
       */
      public Builder clearDynamicId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dynamicId_ = getDefaultInstance().getDynamicId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dynamicId = 2;</code>
       */
      public Builder setDynamicIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dynamicId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList arguments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureArgumentsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          arguments_ = new com.google.protobuf.LazyStringArrayList(arguments_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string arguments = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getArgumentsList() {
        return arguments_.getUnmodifiableView();
      }
      /**
       * <code>repeated string arguments = 3;</code>
       */
      public int getArgumentsCount() {
        return arguments_.size();
      }
      /**
       * <code>repeated string arguments = 3;</code>
       */
      public java.lang.String getArguments(int index) {
        return arguments_.get(index);
      }
      /**
       * <code>repeated string arguments = 3;</code>
       */
      public com.google.protobuf.ByteString
          getArgumentsBytes(int index) {
        return arguments_.getByteString(index);
      }
      /**
       * <code>repeated string arguments = 3;</code>
       */
      public Builder setArguments(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgumentsIsMutable();
        arguments_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string arguments = 3;</code>
       */
      public Builder addArguments(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgumentsIsMutable();
        arguments_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string arguments = 3;</code>
       */
      public Builder addAllArguments(
          java.lang.Iterable<java.lang.String> values) {
        ensureArgumentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, arguments_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string arguments = 3;</code>
       */
      public Builder clearArguments() {
        arguments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string arguments = 3;</code>
       */
      public Builder addArgumentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgumentsIsMutable();
        arguments_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList stdin_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStdinIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          stdin_ = new com.google.protobuf.LazyStringArrayList(stdin_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string stdin = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getStdinList() {
        return stdin_.getUnmodifiableView();
      }
      /**
       * <code>repeated string stdin = 4;</code>
       */
      public int getStdinCount() {
        return stdin_.size();
      }
      /**
       * <code>repeated string stdin = 4;</code>
       */
      public java.lang.String getStdin(int index) {
        return stdin_.get(index);
      }
      /**
       * <code>repeated string stdin = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStdinBytes(int index) {
        return stdin_.getByteString(index);
      }
      /**
       * <code>repeated string stdin = 4;</code>
       */
      public Builder setStdin(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStdinIsMutable();
        stdin_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stdin = 4;</code>
       */
      public Builder addStdin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStdinIsMutable();
        stdin_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stdin = 4;</code>
       */
      public Builder addAllStdin(
          java.lang.Iterable<java.lang.String> values) {
        ensureStdinIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stdin_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stdin = 4;</code>
       */
      public Builder clearStdin() {
        stdin_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stdin = 4;</code>
       */
      public Builder addStdinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStdinIsMutable();
        stdin_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.mackenziehigh.socius.subprocess.ProcessRequest)
    }

    // @@protoc_insertion_point(class_scope:com.mackenziehigh.socius.subprocess.ProcessRequest)
    private static final com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest();
    }

    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProcessRequest>
        PARSER = new com.google.protobuf.AbstractParser<ProcessRequest>() {
      public ProcessRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProcessRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProcessRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProcessRequest> getParserForType() {
      return PARSER;
    }

    public com.mackenziehigh.socius.gpb.subprocess_m.ProcessRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProcessResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mackenziehigh.socius.subprocess.ProcessResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string staticId = 1;</code>
     */
    boolean hasStaticId();
    /**
     * <code>optional string staticId = 1;</code>
     */
    java.lang.String getStaticId();
    /**
     * <code>optional string staticId = 1;</code>
     */
    com.google.protobuf.ByteString
        getStaticIdBytes();

    /**
     * <code>optional string dynamicId = 2;</code>
     */
    boolean hasDynamicId();
    /**
     * <code>optional string dynamicId = 2;</code>
     */
    java.lang.String getDynamicId();
    /**
     * <code>optional string dynamicId = 2;</code>
     */
    com.google.protobuf.ByteString
        getDynamicIdBytes();

    /**
     * <code>optional int64 startTime = 3;</code>
     */
    boolean hasStartTime();
    /**
     * <code>optional int64 startTime = 3;</code>
     */
    long getStartTime();

    /**
     * <code>optional bool alive = 4;</code>
     */
    boolean hasAlive();
    /**
     * <code>optional bool alive = 4;</code>
     */
    boolean getAlive();

    /**
     * <code>repeated string stdout = 5;</code>
     */
    java.util.List<java.lang.String>
        getStdoutList();
    /**
     * <code>repeated string stdout = 5;</code>
     */
    int getStdoutCount();
    /**
     * <code>repeated string stdout = 5;</code>
     */
    java.lang.String getStdout(int index);
    /**
     * <code>repeated string stdout = 5;</code>
     */
    com.google.protobuf.ByteString
        getStdoutBytes(int index);

    /**
     * <code>repeated string stderr = 6;</code>
     */
    java.util.List<java.lang.String>
        getStderrList();
    /**
     * <code>repeated string stderr = 6;</code>
     */
    int getStderrCount();
    /**
     * <code>repeated string stderr = 6;</code>
     */
    java.lang.String getStderr(int index);
    /**
     * <code>repeated string stderr = 6;</code>
     */
    com.google.protobuf.ByteString
        getStderrBytes(int index);
  }
  /**
   * Protobuf type {@code com.mackenziehigh.socius.subprocess.ProcessResponse}
   */
  public  static final class ProcessResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mackenziehigh.socius.subprocess.ProcessResponse)
      ProcessResponseOrBuilder {
    // Use ProcessResponse.newBuilder() to construct.
    private ProcessResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProcessResponse() {
      staticId_ = "";
      dynamicId_ = "";
      startTime_ = 0L;
      alive_ = false;
      stdout_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      stderr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProcessResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              staticId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              dynamicId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              startTime_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              alive_ = input.readBool();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                stdout_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              stdout_.add(bs);
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                stderr_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              stderr_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          stdout_ = stdout_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          stderr_ = stderr_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mackenziehigh.socius.gpb.subprocess_m.internal_static_com_mackenziehigh_socius_subprocess_ProcessResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mackenziehigh.socius.gpb.subprocess_m.internal_static_com_mackenziehigh_socius_subprocess_ProcessResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse.class, com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse.Builder.class);
    }

    private int bitField0_;
    public static final int STATICID_FIELD_NUMBER = 1;
    private volatile java.lang.Object staticId_;
    /**
     * <code>optional string staticId = 1;</code>
     */
    public boolean hasStaticId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string staticId = 1;</code>
     */
    public java.lang.String getStaticId() {
      java.lang.Object ref = staticId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          staticId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string staticId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStaticIdBytes() {
      java.lang.Object ref = staticId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        staticId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DYNAMICID_FIELD_NUMBER = 2;
    private volatile java.lang.Object dynamicId_;
    /**
     * <code>optional string dynamicId = 2;</code>
     */
    public boolean hasDynamicId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string dynamicId = 2;</code>
     */
    public java.lang.String getDynamicId() {
      java.lang.Object ref = dynamicId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dynamicId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dynamicId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDynamicIdBytes() {
      java.lang.Object ref = dynamicId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dynamicId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTTIME_FIELD_NUMBER = 3;
    private long startTime_;
    /**
     * <code>optional int64 startTime = 3;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 startTime = 3;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int ALIVE_FIELD_NUMBER = 4;
    private boolean alive_;
    /**
     * <code>optional bool alive = 4;</code>
     */
    public boolean hasAlive() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool alive = 4;</code>
     */
    public boolean getAlive() {
      return alive_;
    }

    public static final int STDOUT_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList stdout_;
    /**
     * <code>repeated string stdout = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStdoutList() {
      return stdout_;
    }
    /**
     * <code>repeated string stdout = 5;</code>
     */
    public int getStdoutCount() {
      return stdout_.size();
    }
    /**
     * <code>repeated string stdout = 5;</code>
     */
    public java.lang.String getStdout(int index) {
      return stdout_.get(index);
    }
    /**
     * <code>repeated string stdout = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStdoutBytes(int index) {
      return stdout_.getByteString(index);
    }

    public static final int STDERR_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList stderr_;
    /**
     * <code>repeated string stderr = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStderrList() {
      return stderr_;
    }
    /**
     * <code>repeated string stderr = 6;</code>
     */
    public int getStderrCount() {
      return stderr_.size();
    }
    /**
     * <code>repeated string stderr = 6;</code>
     */
    public java.lang.String getStderr(int index) {
      return stderr_.get(index);
    }
    /**
     * <code>repeated string stderr = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStderrBytes(int index) {
      return stderr_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, staticId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dynamicId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, startTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, alive_);
      }
      for (int i = 0; i < stdout_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, stdout_.getRaw(i));
      }
      for (int i = 0; i < stderr_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, stderr_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, staticId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dynamicId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, startTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, alive_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stdout_.size(); i++) {
          dataSize += computeStringSizeNoTag(stdout_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getStdoutList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stderr_.size(); i++) {
          dataSize += computeStringSizeNoTag(stderr_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getStderrList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse)) {
        return super.equals(obj);
      }
            com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse other = (com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse) obj;

      boolean result = true;
      result = result && (hasStaticId() == other.hasStaticId());
      if (hasStaticId()) {
        result = result && getStaticId()
            .equals(other.getStaticId());
      }
      result = result && (hasDynamicId() == other.hasDynamicId());
      if (hasDynamicId()) {
        result = result && getDynamicId()
            .equals(other.getDynamicId());
      }
      result = result && (hasStartTime() == other.hasStartTime());
      if (hasStartTime()) {
        result = result && (getStartTime()
            == other.getStartTime());
      }
      result = result && (hasAlive() == other.hasAlive());
      if (hasAlive()) {
        result = result && (getAlive()
            == other.getAlive());
      }
      result = result && getStdoutList()
          .equals(other.getStdoutList());
      result = result && getStderrList()
          .equals(other.getStderrList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStaticId()) {
        hash = (37 * hash) + STATICID_FIELD_NUMBER;
        hash = (53 * hash) + getStaticId().hashCode();
      }
      if (hasDynamicId()) {
        hash = (37 * hash) + DYNAMICID_FIELD_NUMBER;
        hash = (53 * hash) + getDynamicId().hashCode();
      }
      if (hasStartTime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartTime());
      }
      if (hasAlive()) {
        hash = (37 * hash) + ALIVE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getAlive());
      }
      if (getStdoutCount() > 0) {
        hash = (37 * hash) + STDOUT_FIELD_NUMBER;
        hash = (53 * hash) + getStdoutList().hashCode();
      }
      if (getStderrCount() > 0) {
        hash = (37 * hash) + STDERR_FIELD_NUMBER;
        hash = (53 * hash) + getStderrList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mackenziehigh.socius.subprocess.ProcessResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mackenziehigh.socius.subprocess.ProcessResponse)
        com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return  com.mackenziehigh.socius.gpb.subprocess_m.internal_static_com_mackenziehigh_socius_subprocess_ProcessResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return  com.mackenziehigh.socius.gpb.subprocess_m.internal_static_com_mackenziehigh_socius_subprocess_ProcessResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse.class, com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse.Builder.class);
      }

      // Construct using com.mackenziehigh.socius.subprocess.Subprocess.ProcessResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        staticId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        dynamicId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        startTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        alive_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        stdout_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        stderr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return  com.mackenziehigh.socius.gpb.subprocess_m.internal_static_com_mackenziehigh_socius_subprocess_ProcessResponse_descriptor;
      }

      public com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse getDefaultInstanceForType() {
        return  com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse.getDefaultInstance();
      }

      public com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse build() {
                com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse buildPartial() {
                com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse result = new com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.staticId_ = staticId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dynamicId_ = dynamicId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.alive_ = alive_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          stdout_ = stdout_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.stdout_ = stdout_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          stderr_ = stderr_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.stderr_ = stderr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse) {
          return mergeFrom((com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse other) {
        if (other == com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse.getDefaultInstance()) return this;
        if (other.hasStaticId()) {
          bitField0_ |= 0x00000001;
          staticId_ = other.staticId_;
          onChanged();
        }
        if (other.hasDynamicId()) {
          bitField0_ |= 0x00000002;
          dynamicId_ = other.dynamicId_;
          onChanged();
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasAlive()) {
          setAlive(other.getAlive());
        }
        if (!other.stdout_.isEmpty()) {
          if (stdout_.isEmpty()) {
            stdout_ = other.stdout_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureStdoutIsMutable();
            stdout_.addAll(other.stdout_);
          }
          onChanged();
        }
        if (!other.stderr_.isEmpty()) {
          if (stderr_.isEmpty()) {
            stderr_ = other.stderr_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureStderrIsMutable();
            stderr_.addAll(other.stderr_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
                com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object staticId_ = "";
      /**
       * <code>optional string staticId = 1;</code>
       */
      public boolean hasStaticId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string staticId = 1;</code>
       */
      public java.lang.String getStaticId() {
        java.lang.Object ref = staticId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            staticId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string staticId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStaticIdBytes() {
        java.lang.Object ref = staticId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          staticId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string staticId = 1;</code>
       */
      public Builder setStaticId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        staticId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string staticId = 1;</code>
       */
      public Builder clearStaticId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        staticId_ = getDefaultInstance().getStaticId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string staticId = 1;</code>
       */
      public Builder setStaticIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        staticId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dynamicId_ = "";
      /**
       * <code>optional string dynamicId = 2;</code>
       */
      public boolean hasDynamicId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string dynamicId = 2;</code>
       */
      public java.lang.String getDynamicId() {
        java.lang.Object ref = dynamicId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dynamicId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dynamicId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDynamicIdBytes() {
        java.lang.Object ref = dynamicId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dynamicId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dynamicId = 2;</code>
       */
      public Builder setDynamicId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dynamicId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dynamicId = 2;</code>
       */
      public Builder clearDynamicId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dynamicId_ = getDefaultInstance().getDynamicId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dynamicId = 2;</code>
       */
      public Builder setDynamicIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dynamicId_ = value;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <code>optional int64 startTime = 3;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 startTime = 3;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>optional int64 startTime = 3;</code>
       */
      public Builder setStartTime(long value) {
        bitField0_ |= 0x00000004;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 startTime = 3;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private boolean alive_ ;
      /**
       * <code>optional bool alive = 4;</code>
       */
      public boolean hasAlive() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool alive = 4;</code>
       */
      public boolean getAlive() {
        return alive_;
      }
      /**
       * <code>optional bool alive = 4;</code>
       */
      public Builder setAlive(boolean value) {
        bitField0_ |= 0x00000008;
        alive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool alive = 4;</code>
       */
      public Builder clearAlive() {
        bitField0_ = (bitField0_ & ~0x00000008);
        alive_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList stdout_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStdoutIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          stdout_ = new com.google.protobuf.LazyStringArrayList(stdout_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string stdout = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getStdoutList() {
        return stdout_.getUnmodifiableView();
      }
      /**
       * <code>repeated string stdout = 5;</code>
       */
      public int getStdoutCount() {
        return stdout_.size();
      }
      /**
       * <code>repeated string stdout = 5;</code>
       */
      public java.lang.String getStdout(int index) {
        return stdout_.get(index);
      }
      /**
       * <code>repeated string stdout = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStdoutBytes(int index) {
        return stdout_.getByteString(index);
      }
      /**
       * <code>repeated string stdout = 5;</code>
       */
      public Builder setStdout(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStdoutIsMutable();
        stdout_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stdout = 5;</code>
       */
      public Builder addStdout(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStdoutIsMutable();
        stdout_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stdout = 5;</code>
       */
      public Builder addAllStdout(
          java.lang.Iterable<java.lang.String> values) {
        ensureStdoutIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stdout_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stdout = 5;</code>
       */
      public Builder clearStdout() {
        stdout_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stdout = 5;</code>
       */
      public Builder addStdoutBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStdoutIsMutable();
        stdout_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList stderr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStderrIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          stderr_ = new com.google.protobuf.LazyStringArrayList(stderr_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string stderr = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getStderrList() {
        return stderr_.getUnmodifiableView();
      }
      /**
       * <code>repeated string stderr = 6;</code>
       */
      public int getStderrCount() {
        return stderr_.size();
      }
      /**
       * <code>repeated string stderr = 6;</code>
       */
      public java.lang.String getStderr(int index) {
        return stderr_.get(index);
      }
      /**
       * <code>repeated string stderr = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStderrBytes(int index) {
        return stderr_.getByteString(index);
      }
      /**
       * <code>repeated string stderr = 6;</code>
       */
      public Builder setStderr(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStderrIsMutable();
        stderr_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stderr = 6;</code>
       */
      public Builder addStderr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStderrIsMutable();
        stderr_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stderr = 6;</code>
       */
      public Builder addAllStderr(
          java.lang.Iterable<java.lang.String> values) {
        ensureStderrIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stderr_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stderr = 6;</code>
       */
      public Builder clearStderr() {
        stderr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stderr = 6;</code>
       */
      public Builder addStderrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStderrIsMutable();
        stderr_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.mackenziehigh.socius.subprocess.ProcessResponse)
    }

    // @@protoc_insertion_point(class_scope:com.mackenziehigh.socius.subprocess.ProcessResponse)
    private static final com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse();
    }

    public static com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProcessResponse>
        PARSER = new com.google.protobuf.AbstractParser<ProcessResponse>() {
      public ProcessResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProcessResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProcessResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProcessResponse> getParserForType() {
      return PARSER;
    }

    public com.mackenziehigh.socius.gpb.subprocess_m.ProcessResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mackenziehigh_socius_subprocess_ProcessRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mackenziehigh_socius_subprocess_ProcessRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mackenziehigh_socius_subprocess_ProcessResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mackenziehigh_socius_subprocess_ProcessResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Subprocess.proto\022#com.mackenziehigh.so" +
      "cius.subprocess\"W\n\016ProcessRequest\022\020\n\010sta" +
      "ticId\030\001 \001(\t\022\021\n\tdynamicId\030\002 \001(\t\022\021\n\targume" +
      "nts\030\003 \003(\t\022\r\n\005stdin\030\004 \003(\t\"x\n\017ProcessRespo" +
      "nse\022\020\n\010staticId\030\001 \001(\t\022\021\n\tdynamicId\030\002 \001(\t" +
      "\022\021\n\tstartTime\030\003 \001(\003\022\r\n\005alive\030\004 \001(\010\022\016\n\006st" +
      "dout\030\005 \003(\t\022\016\n\006stderr\030\006 \003(\tB%\n#com.macken" +
      "ziehigh.socius.subprocess"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mackenziehigh_socius_subprocess_ProcessRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mackenziehigh_socius_subprocess_ProcessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mackenziehigh_socius_subprocess_ProcessRequest_descriptor,
        new java.lang.String[] { "StaticId", "DynamicId", "Arguments", "Stdin", });
    internal_static_com_mackenziehigh_socius_subprocess_ProcessResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mackenziehigh_socius_subprocess_ProcessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mackenziehigh_socius_subprocess_ProcessResponse_descriptor,
        new java.lang.String[] { "StaticId", "DynamicId", "StartTime", "Alive", "Stdout", "Stderr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
